const MYSQL_ERR_NO = {
    CONNECTION_ERROR: -4078,
};

const PLAYFAB_ERR_NO = {
    SUCCESS: 200,
    BAD_REQUEST: 400,
};

const TX_TYPE = {
    MINT: 1,
    EXCHANGE: 2,
    BURN: 3,
    TRANSFER: 4,
    DEPOSIT: 5,
    WITHDRAW: 6,
};

const RET_CODE = {
    SUCCESS: 0,
    FAILED: 1,
    INVALID_PARAMETERS: 100,
    NOT_REGISTERED_WALLET_ADDRESS: 101,
    NOT_REGISTERED_PLAYFAB: 102,
    INSUFFICIANT_BALANCE: 103,
    DUPLICATE_WALLET_ADDRESS: 104,
    DUPLICATE_EMAIL_ADDRESS: 105,
    PENDING_TO_REGISTER_EMAIL_ADDRESS: 106,
    FAILED_TO_SEND_EMAIL: 107,
    TOKEN_EXPIRED: 108,
};

module.exports = {
    MYSQL_ERR_NO,
    PLAYFAB_ERR_NO,
    TX_TYPE,
    RET_CODE,
};
